# Generated by Django 4.2 on 2024-09-29 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Melouk_Eltibah', '0002_remove_melouk_eltibah_inquiry_inquiryid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='melouk_eltibah_order',
            name='Cash',
        ),
    ]
