# Generated by Django 4.2 on 2024-10-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Melouk_Eltibah', '0004_alter_melouk_eltibah_orderdetail_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='melouk_eltibah_feedback',
            name='feedback',
            field=models.TextField(max_length=250, verbose_name='FeedBack'),
        ),
        migrations.AlterField(
            model_name='melouk_eltibah_inquiry',
            name='Details',
            field=models.TextField(max_length=250, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='melouk_eltibah_order',
            name='Shipping',
            field=models.TextField(max_length=250, verbose_name='Shipping'),
        ),
    ]
