# Generated by Django 4.2 on 2024-09-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Designer')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name_plural': 'Designer',
            },
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Governorate', models.CharField(max_length=50, unique=True, verbose_name='Governorate')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name_plural': 'City',
            },
        ),
        migrations.CreateModel(
            name='Inquiry_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inq_Feedback', models.CharField(max_length=50, unique=True, verbose_name='inq_Feedback')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name_plural': 'Inquiry_Feedback',
            },
        ),
        migrations.CreateModel(
            name='inquiry_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry', models.CharField(max_length=50, unique=True, verbose_name='Inquiry')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name_plural': 'inquiry_Status',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item', models.CharField(max_length=50, unique=True, verbose_name='Item')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Order_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(max_length=300, unique=True, verbose_name='Feedback')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name_plural': 'Order_Feedback',
            },
        ),
        migrations.CreateModel(
            name='Order_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=300, unique=True, verbose_name='Status')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name_plural': 'Order_Status',
            },
        ),
        migrations.CreateModel(
            name='SourceChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=300, unique=True, verbose_name='Source')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name_plural': 'Source',
            },
        ),
    ]
