# Generated by Django 4.2 on 2024-09-28 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dr_Print', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dr_print_inquiry',
            name='InquiryId',
        ),
        migrations.RemoveField(
            model_name='dr_print_order',
            name='OrderId',
        ),
    ]
