# Generated by Django 4.2 on 2024-09-29 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dr_Print', '0002_remove_dr_print_inquiry_inquiryid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dr_print_order',
            name='Cash',
        ),
    ]
