# Generated by Django 4.2 on 2024-09-28 18:39

import Etbaly_Shokran.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CRM_Data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etbaly_Shokran_Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=100, unique=True, verbose_name='Company')),
                ('Client', models.CharField(max_length=100, verbose_name='Client')),
                ('Phone_1', models.CharField(max_length=11, unique=True, verbose_name='Phone 1 ')),
                ('Phone_2', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Phone 2 ')),
                ('Address', models.TextField(max_length=250, verbose_name='Address')),
                ('Email', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Email')),
                ('Note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Note')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Governorate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Etbaly_Shokran_Customer_city', to='CRM_Data.governorate')),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Etbaly_Shokran_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderId', models.CharField(blank=True, max_length=10, null=True)),
                ('Design', models.FileField(blank=True, null=True, upload_to=Etbaly_Shokran.models.user_directory_path)),
                ('Transfer', models.IntegerField(default=0, verbose_name='Transfer')),
                ('Cash', models.IntegerField(default=0, verbose_name='Cash')),
                ('Discount', models.IntegerField(default=0, verbose_name='Discount')),
                ('Delivery', models.IntegerField(default=0, verbose_name='Delivery')),
                ('Design_Fees', models.IntegerField(default=0, verbose_name='Design_Fees')),
                ('Shipping', models.CharField(max_length=100, verbose_name='Shipping')),
                ('Order_Note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Note')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Etbaly_Shokran_order_customer', to='Etbaly_Shokran.etbaly_shokran_customer')),
                ('Designer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Etbaly_Shokran_order_Designer', to='CRM_Data.designer')),
                ('Feedback', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Etbaly_Shokran_Order_Feedback', to='CRM_Data.order_feedback')),
                ('Sales', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Etbaly_Shokran_Order_Sales', to=settings.AUTH_USER_MODEL)),
                ('Source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Etbaly_Shokran_order_Source', to='CRM_Data.sourcechannel')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Etbaly_Shokran_order_status', to='CRM_Data.order_status')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Etbaly_Shokran_OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=100, verbose_name='Item_Name')),
                ('Quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('Price', models.IntegerField(default=0, verbose_name='Price')),
                ('Note', models.CharField(blank=True, max_length=50, null=True, verbose_name='Note')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Etbaly_Shokran_Item_Category', to='CRM_Data.item')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Etbaly_Shokran_order_Detail', to='Etbaly_Shokran.etbaly_shokran_order')),
            ],
            options={
                'verbose_name_plural': 'Order_Items',
            },
        ),
        migrations.CreateModel(
            name='Etbaly_Shokran_Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InquiryId', models.IntegerField(blank=True, null=True)),
                ('Details', models.CharField(max_length=250, verbose_name='Details')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Note', models.CharField(default='No_Note', max_length=50, verbose_name='Note')),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Etbaly_Shokran_order_Inquiry', to='Etbaly_Shokran.etbaly_shokran_order')),
                ('Sales', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Etbaly_Shokran_Inquiry_Sales', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Etbaly_Shokran_inquiry_Status', to='CRM_Data.inquiry_status')),
            ],
            options={
                'verbose_name_plural': 'Inquiry',
            },
        ),
        migrations.CreateModel(
            name='Etbaly_Shokran_FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=250, verbose_name='FeedBack')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(default='No_Note', max_length=50, verbose_name='Note')),
                ('Cus_Service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Etbaly_Shokran_FeedBack_Cus_Service', to=settings.AUTH_USER_MODEL)),
                ('Inquiry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Etbaly_Shokran_FeedBack_Inquiry', to='Etbaly_Shokran.etbaly_shokran_inquiry')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Etbaly_Shokran_Inquiry_Feedback', to='CRM_Data.inquiry_feedback')),
            ],
            options={
                'verbose_name_plural': 'FeedBack',
            },
        ),
    ]
