# Generated by Django 4.2 on 2024-09-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Etbaly_Shokran', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etbaly_shokran_inquiry',
            name='InquiryId',
        ),
        migrations.RemoveField(
            model_name='etbaly_shokran_order',
            name='OrderId',
        ),
    ]
