# Generated by Django 4.2 on 2024-09-29 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Etbaly_Shokran', '0002_remove_etbaly_shokran_inquiry_inquiryid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etbaly_shokran_order',
            name='Cash',
        ),
    ]
