# Generated by Django 4.2 on 2024-10-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Etbaly_Shokran', '0004_alter_etbaly_shokran_orderdetail_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etbaly_shokran_feedback',
            name='feedback',
            field=models.TextField(max_length=250, verbose_name='FeedBack'),
        ),
        migrations.AlterField(
            model_name='etbaly_shokran_inquiry',
            name='Details',
            field=models.TextField(max_length=250, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='etbaly_shokran_order',
            name='Shipping',
            field=models.TextField(max_length=250, verbose_name='Shipping'),
        ),
    ]
