# Generated by Django 4.2 on 2024-10-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Print_Square', '0003_remove_print_square_order_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='print_square_orderdetail',
            name='Item_Name',
            field=models.TextField(max_length=250, verbose_name='Item_Name'),
        ),
    ]
